In [55]:
import numpy as np

In [56]:
X = np.random.uniform(0, 1, [5, 5])
X = np.round(X, 2)
print(X)

[[0.85 0.93 0.86 0.51 0.65]
 [0.3  0.26 0.42 0.47 0.86]
 [0.99 0.27 0.29 0.79 0.69]
 [0.57 0.2  0.04 0.11 0.64]
 [0.01 0.71 0.29 0.19 0.15]]


In [57]:
X = np.random.normal(0, 1, [5, 5])
#X = np.round(X, 2)
print(np.average(X), np.var(X))

-0.03928149433890831 1.0888241122230518


In [58]:
X_T = np.transpose(X)
print(X, X_T, sep = '\n')

[[-0.67920736 -0.40073121 -0.07547931 -0.14994382  0.75156292]
 [ 1.45701232  0.96151097  0.09287382 -1.07661737 -1.20555844]
 [ 0.36903229  0.2663304  -0.72965655  0.1592379   1.04289935]
 [ 0.74556361 -2.39857433  0.07109471  2.18594752 -0.17713955]
 [ 0.10322009  0.78520389  0.51627234 -1.66267395 -1.9342176 ]]
[[-0.67920736  1.45701232  0.36903229  0.74556361  0.10322009]
 [-0.40073121  0.96151097  0.2663304  -2.39857433  0.78520389]
 [-0.07547931  0.09287382 -0.72965655  0.07109471  0.51627234]
 [-0.14994382 -1.07661737  0.1592379   2.18594752 -1.66267395]
 [ 0.75156292 -1.20555844  1.04289935 -0.17713955 -1.9342176 ]]


In [59]:
X_inv = np.linalg.inv(X)
print(X_inv)
# print(np.dot(X, X_inv))
X_mul_X_inv = np.dot(X, X_inv)
print(X_mul_X_inv)
print(np.eye(5) == np.round(np.dot(X, X_inv), 0))

[[ 0.5073304   1.02798993 -0.37698927  0.07156397 -0.6534166 ]
 [-1.13868715 -0.20414595 -0.23674152 -0.46580572 -0.40019806]
 [ 0.97984818  1.56245452 -2.76367746 -0.51089662 -2.03645655]
 [-1.37279477 -0.55523513 -0.10330425 -0.08180534 -0.23555686]
 [ 1.00642436  0.86631414 -0.76509084 -0.25132219 -1.0554111 ]]
[[ 1.00000000e+00 -1.62068157e-16  3.30159732e-18  4.34374733e-17
   8.62679031e-17]
 [ 3.57337993e-17  1.00000000e+00 -1.10944443e-17 -7.61747120e-17
   3.71174829e-17]
 [ 1.82990368e-16 -7.40523561e-17  1.00000000e+00 -5.04825808e-17
   7.71763057e-17]
 [ 2.42726635e-17  1.53354472e-17  9.18133588e-17  1.00000000e+00
   2.97544169e-16]
 [ 1.60420472e-16  4.42013867e-16  1.24370113e-16 -9.78782265e-17
   1.00000000e+00]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


1. Consider $w_1 = (XX^T + \gamma I)^{-1}Xy \in R^D,\quad w_2 = X(X^{T}X + \gamma I)^{-1}y \in R^D$.
Make a python program $X_{D\times N}\sim Unif(0, 1),\quad y_{N\times 1}\sim Unif(0, 1)$ see whether $w_1=w_2$ or not.

2. Same thing but $X_{D\times N}\sim N(0, 1),\quad y_{N\times 1}\sim N(0, 1)$

부동소수점 이슈 파훼법
1. 반올림해서 return, np.array_equal()로 확인
2. 일단 return 하고 np.allclose()로 확인
allclose() : 오차(기본값이 1e-5랬나) 보다 작으면 같다 쳐줌.

In [60]:
D, N = 4, 3
Gamma = 0.5

def w1(X, y):
    X_mul_X_t = np.dot(X, np.transpose(X))
    I = np.eye(D)
    XXt_plus_gamma_I = X_mul_X_t + Gamma * I
    result = np.dot(np.dot(np.linalg.inv(XXt_plus_gamma_I), X), y)
    return np.round(result, 5)
    # return result

def w2(X, y):
    X_t_mul_X = np.dot(np.transpose(X), X)
    I = np.eye(N)
    XtX_plus_gamma_I = X_t_mul_X + Gamma * I
    result = np.dot(np.dot(X, np.linalg.inv(XtX_plus_gamma_I)), y)
    return np.round(result, 5)
    # return result

In [61]:
X_uni = np.random.uniform(0, 1, [D, N])
y_uni = np.random.uniform(0, 1, N)

w1_uni = w1(X_uni, y_uni)
w2_uni = w2(X_uni, y_uni)
print("w1 :", w1_uni)
print("w2 :", w2_uni)

print("w1 == w2 ? :", np.array_equal(w1_uni, w2_uni))
# print("w1 == w2 ? :", np.allclose(w1_uni, w2_uni))

w1 : [0.3943  0.12342 0.21989 0.56742]
w2 : [0.3943  0.12342 0.21989 0.56742]
w1 == w2 ? : True
