In [11]:
import numpy as np

In [12]:
X = np.random.uniform(0, 1, [5, 5])
X = np.round(X, 2)
print(X)

[[0.56 0.19 0.92 0.13 0.01]
 [0.62 0.42 0.24 0.11 0.63]
 [0.94 0.38 0.33 0.65 0.26]
 [0.23 0.53 0.46 0.36 0.74]
 [0.42 0.85 0.42 0.78 0.91]]


In [13]:
X = np.random.normal(0, 1, [5, 5])
#X = np.round(X, 2)
print(np.average(X), np.var(X))

-0.17026679747324966 0.8304272063620387


In [14]:
X_T = np.transpose(X)
print(X, X_T, sep = '\n')

[[ 1.17567986 -1.19108501 -1.06909029  0.68486039  0.80675259]
 [-1.05449724 -0.08043953 -1.1003684  -0.10126536  0.85769207]
 [ 0.42333995 -1.15906415 -0.0948874   0.50658645  1.29960716]
 [ 0.59263257 -0.84966039 -0.39979848 -1.95454066  0.73906815]
 [-0.07668372 -1.3656347  -0.12999962 -1.38893386  0.67305971]]
[[ 1.17567986 -1.05449724  0.42333995  0.59263257 -0.07668372]
 [-1.19108501 -0.08043953 -1.15906415 -0.84966039 -1.3656347 ]
 [-1.06909029 -1.1003684  -0.0948874  -0.39979848 -0.12999962]
 [ 0.68486039 -0.10126536  0.50658645 -1.95454066 -1.38893386]
 [ 0.80675259  0.85769207  1.29960716  0.73906815  0.67305971]]


In [15]:
X_inv = np.linalg.inv(X)
print(X_inv)
# print(np.dot(X, X_inv))
X_mul_X_inv = np.dot(X, X_inv)
print(X_mul_X_inv)
print(np.eye(5) == np.round(np.dot(X, X_inv), 0))

[[ 0.2164273  -0.33931377  0.08788387  0.5182819  -0.565829  ]
 [-0.35182144  0.19049897  0.25551951  0.71247095 -1.09677666]
 [-0.57421977 -0.39848315  0.62914321 -0.01902807  0.00215901]
 [ 0.15239799 -0.00797386  0.14864196 -0.42217481  0.00405826]
 [-0.48560437  0.25444152  0.9567172   0.62976924 -0.79527685]]
[[ 1.00000000e+00  2.65227683e-17  1.03281861e-16  1.62741084e-16
  -6.61476459e-17]
 [ 4.32574951e-17  1.00000000e+00 -2.94236808e-17  4.42411707e-17
  -2.48154973e-16]
 [-1.46440351e-16  8.70899557e-17  1.00000000e+00  1.60931519e-16
  -2.79739354e-16]
 [-5.72726405e-17  2.48529753e-17  3.88866756e-17  1.00000000e+00
  -1.92366470e-16]
 [-8.22636315e-17  4.02280757e-17 -1.35848965e-17  1.00572909e-16
   1.00000000e+00]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [44]:
D, N = 4, 3
Gamma = 0.5

def w1(X, y):
    X_mul_X_t = np.dot(X, np.transpose(X))
    I = np.eye(D)
    XXt_plus_gamma_I = X_mul_X_t + Gamma * I
    result = np.dot(np.dot(np.linalg.inv(XXt_plus_gamma_I), X), y)
    return np.round(result, 5)

def w2(X, y):
    X_t_mul_X = np.dot(np.transpose(X), X)
    I = np.eye(N)
    XtX_plus_gamma_I = X_t_mul_X + Gamma * I
    result = np.dot(np.dot(X, np.linalg.inv(XtX_plus_gamma_I)), y)
    return np.round(result, 5)

In [47]:
X_uni = np.random.uniform(0, 1, [D, N])
y_uni = np.random.uniform(0, 1, N)

print("w1 :", w1(X_uni, y_uni))
print("w2 :", w2(X_uni, y_uni))
print("w1 == w2 ?", np.array_equal(w1(X_uni, y_uni), w2(X_uni, y_uni)))

w1 : [ 0.09396  0.19392  0.14601 -0.11384]
w2 : [ 0.09396  0.19392  0.14601 -0.11384]
w1 == w2 ? True
